# Generated by Django 4.2 on 2023-04-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=200, verbose_name='Autó márkája')),
            ],
        ),
        migrations.CreateModel(
            name='Szolgaltatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neve', models.CharField(blank=True, max_length=200, verbose_name='Szolgáltatás')),
                ('ara', models.CharField(blank=True, max_length=200, verbose_name='Ára')),
            ],
        ),
        migrations.CreateModel(
            name='Megrendelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(blank=True, max_length=100, verbose_name='Adja meg a teljes nevét!')),
                ('telefonszam', models.CharField(blank=True, max_length=11, verbose_name='Adja meg a telefonszámot!')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adja meg a email cimét!')),
                ('auto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Carappointment.auto')),
                ('szolgaltatas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Carappointment.szolgaltatas')),
            ],
        ),
    ]
