# Generated by Django 4.2 on 2023-04-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carappointment', '0002_remove_megrendelo_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megrendelo',
            name='auto',
        ),
        migrations.AddField(
            model_name='megrendelo',
            name='auto',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Carappointment.auto'),
            preserve_default=False,
        ),
    ]
