# Generated by Django 4.2 on 2023-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carappointment', '0004_szolgaltatas_ido'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='evjarat',
            field=models.IntegerField(default=2, verbose_name='Évjárat'),
            preserve_default=False,
        ),
    ]
