# Generated by Django 4.2 on 2023-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carappointment', '0005_auto_evjarat'),
    ]

    operations = [
        migrations.AddField(
            model_name='szolgaltatas',
            name='kategoria',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kategória'),
        ),
    ]
