# Generated by Django 4.2 on 2023-04-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carappointment', '0006_szolgaltatas_kategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='evjarat',
        ),
    ]
