# Generated by Django 4.2 on 2023-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carappointment', '0007_remove_auto_evjarat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szolgaltatas',
            name='ido',
            field=models.CharField(blank=True, max_length=200, verbose_name='Munkaidő'),
        ),
    ]
