# Generated by Django 4.2 on 2023-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carappointment', '0008_alter_szolgaltatas_ido'),
    ]

    operations = [
        migrations.AddField(
            model_name='megrendelo',
            name='datum',
            field=models.CharField(blank=True, max_length=200, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='szolgaltatas',
            name='ara',
            field=models.IntegerField(blank=True, max_length=200, verbose_name='Ára'),
        ),
        migrations.AlterField(
            model_name='szolgaltatas',
            name='ido',
            field=models.IntegerField(blank=True, max_length=200, verbose_name='Munkaidő'),
        ),
    ]
